apiVersion: v1
kind: Service
metadata:
  name: opc-server-3dpr-service
spec:
  selector:
    app: opc-server-3dpr
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 26543
      targetPort: 26543